apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-training
spec:
  selector:
    matchLabels:
      app: devops-training
  template:
    metadata:
      labels:
        app: devops-training
    spec:
      containers:
      - name: devops-training
        image: 9060/spring-boot-mongo
        ports:
            - name: http
              containerPort: 8080
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: devops-training-app-service
  labels:
    app: devops-training
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31884
    protocol: TCP
    name: http
  selector:
    app: devops-training
